[package]
name = "quotes_server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossbeam-channel = "0.5"
env_logger = "0.11"
log = "0.4"
quotes_lib = { path = "../quotes_lib" }
rand = "0.9.2"
